#!/usr/bin/env bash
set -e
shopt -s expand_aliases

NAME=""

for arg in "$@"
do
    if [ "$arg" == "--new" ]; then
        NEW=ture
    elif [ "$arg" == "--gpus" ]; then
        GPUS=ture
    elif [ "$arg" == -* ]; then
        echo "Unknown option $arg"
        exit 1
    else
        if [ "$NAME" != "" ]; then
            echo "Cannot supply multiple container names"
            exit 1
        fi

        NAME="$arg"
    fi
done

if [ -z $NAME ]
  then
    echo "No container name supplied"
    exit 1
fi

if [ -v NEW ]; then
    DOCKER_BUILDKIT=1 docker build -t $NAME-img .

    if [ -v GPUS ]; then
        docker run -p 2222:22 --gpus all --hostname=$NAME --name $NAME -it $NAME-img
    else
        docker run -p 2222:22 --hostname=$NAME --name $NAME -it $NAME-img
    fi
else
    docker start -ia $NAME
fi
